<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Bundle\Block\Sales\Order\Items\Renderer */ ?>

<?php
$parentItem = $block->getItem();
$type = $block->getType();
$items = array_merge([$parentItem->getOrderItem()], $parentItem->getOrderItem()->getChildrenItems());

$_index = 0;
$_order = $block->getOrder();
$block->setStoreId($_order->getStoreId());
?>
<?php if ($block->getItemOptions() || $parentItem->getDescription() || $this->helper('Magento\GiftMessage\Helper\Message')->isMessagesAllowed('order_item', $parentItem) && $parentItem->getGiftMessageId()): ?>
    <?php $_showlastRow = true ?>
<?php else: ?>
    <?php $_showlastRow = false ?>
<?php endif ?>

<?php $_prevOptionId = '' ?>
<?php
$i = 1;
?>
<div class="bundle-item <?= /** @noEscape */ $block->getIndexKey() ?>" style="border-bottom: 1px solid #ddd;">
    <?php foreach ($items

    as $_item): ?>
    <?php
    // As part of invoice item renderer logic, the order is set on each invoice item.
    // In the case of a bundle product, this template takes over rendering its children,
    // so it is necessary to pass the order along to each child.
    $_item->setOrder($_order);
    ?>
    <div class="mp-row">
        <div class="mp-item">
            <?php if ($_item->getParentItem()): ?>
                <?php $attributes = $block->getSelectionAttributes($_item) ?>
                <?php if ($_prevOptionId != $attributes['option_id']): ?>
                    <div>
                        <strong><em><?= /* @noEscape */
                                $attributes['option_label'] ?></em></strong>
                    </div>
                    <?php $_prevOptionId = $attributes['option_id'] ?>
                <?php endif ?>
            <?php endif ?>

            <?php if (!$_item->getParentItem()): ?>
            <div class="item-info">
                <p class="product-name"><?= $block->escapeHtml($_item->getName()) ?></p>
                <p class="sku"><?= /* @noEscape */
                    __('SKU: %1', $block->escapeHtml($_item->getSku())) ?></p>
            </div>
        </div>
        <?php else: ?>
        <div class="item-info">
            <p><?= $block->getValueHtml($_item) ?></p>
            <?= /** @noEscape */ '<p class="mp-invoice-barcode"><barcode code="' . $_item->getSku() . '" type="C39E" size="0.8"  /></p>' ?>
        </div>
    </div>
    <div class="mp-qty">
        <?php
        if (isset($_item->getProductOptions()['info_buyRequest']) && isset($_item->getProductOptions()['info_buyRequest']['bundle_option_qty'])) {
            $bundleOptionQty = $_item->getProductOptions()['info_buyRequest']['bundle_option_qty'];
            $qty = $bundleOptionQty[$i] * $parentItem->getQty();
            $i++;
        } else {
            $qty = __('N/A');
        }
        ?>
        <span><?= /* @noEscape */
            $qty ?></span>
    </div>
    <div class="mp-price">
        <?= /* @noEscape */
        $_order->formatPrice($_item->getPrice()) ?>
    </div>
<?php endif ?>
</div>
    <div class="clr"></div>
<?php endforeach ?>

<?php if ($_showlastRow): ?>
    <div class="mp-row">
        <div class="item-extra">
            <?php if ($block->getItemOptions()): ?>
                <div>
                    <?php foreach ($block->getItemOptions() as $option): ?>
                        <div><strong><em><?= /* @noEscape */
                                    $option['label'] ?></em></strong></div>
                        <div><?= /* @noEscape */
                            $option['value'] ?></div>
                    <?php endforeach ?>
                </div>
            <?php endif ?>
            <?= $block->escapeHtml($_item->getDescription()) ?>
        </div>
    </div>
<?php endif ?>
</div>
<div class="clr"></div>
