<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_AutoCancelOrder
 * @author     Extension Team
 * @copyright  Copyright (c) 2017-2018 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>
<?php
// @codingStandardsIgnoreFile

/**
 * @var $block \Bss\AutoCancelOrder\Block\Adminhtml\System\Config\Button\ApplyNow
 * @var $block \Bss\AutoCancelOrder\Block\Adminhtml\System\Config\Button\ShowLog
 */
?>
<div class="pp-buttons-container">
    <?php echo $block->getButtonHtml() ?>
</div>
